/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.1 */
/* C:\lscc\diamond\3.12\ispfpga\bin\nt64\scuba.exe -w -n FIFO -lang verilog -synth synplify -bus_exp 7 -bb -arch mg5a00 -type ebfifo -depth 4096 -width 16 -depth 4096 -regout -no_enable -pe -1 -pf -1 -fill  */
/* Mon Jul 18 21:10:37 2022 */


`timescale 1 ns / 1 ps
module FIFO (Data, Clock, WrEn, RdEn, Reset, Q, WCNT, Empty, Full)/* synthesis NGD_DRC_MASK=1 */;
    input wire [15:0] Data;
    input wire Clock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    output wire [15:0] Q;
    output wire [12:0] WCNT;
    output wire Empty;
    output wire Full;

    wire invout_1;
    wire invout_0;
    wire rden_i_inv;
    wire fcnt_en;
    wire empty_i;
    wire empty_d;
    wire full_i;
    wire full_d;
    wire ifcount_0;
    wire ifcount_1;
    wire bdcnt_bctr_ci;
    wire ifcount_2;
    wire ifcount_3;
    wire co0;
    wire ifcount_4;
    wire ifcount_5;
    wire co1;
    wire ifcount_6;
    wire ifcount_7;
    wire co2;
    wire ifcount_8;
    wire ifcount_9;
    wire co3;
    wire ifcount_10;
    wire ifcount_11;
    wire co4;
    wire ifcount_12;
    wire co6;
    wire cnt_con;
    wire co5;
    wire cmp_ci;
    wire rden_i;
    wire co0_1;
    wire co1_1;
    wire co2_1;
    wire co3_1;
    wire co4_1;
    wire co5_1;
    wire cmp_le_1;
    wire cmp_le_1_c;
    wire cmp_ci_1;
    wire fcount_0;
    wire fcount_1;
    wire co0_2;
    wire fcount_2;
    wire fcount_3;
    wire co1_2;
    wire fcount_4;
    wire fcount_5;
    wire co2_2;
    wire fcount_6;
    wire fcount_7;
    wire co3_2;
    wire fcount_8;
    wire fcount_9;
    wire co4_2;
    wire wren_i;
    wire fcount_10;
    wire fcount_11;
    wire co5_2;
    wire wren_i_inv;
    wire fcount_12;
    wire cmp_ge_d1;
    wire cmp_ge_d1_c;
    wire iwcount_0;
    wire iwcount_1;
    wire w_ctr_ci;
    wire wcount_0;
    wire wcount_1;
    wire iwcount_2;
    wire iwcount_3;
    wire co0_3;
    wire wcount_2;
    wire wcount_3;
    wire iwcount_4;
    wire iwcount_5;
    wire co1_3;
    wire wcount_4;
    wire wcount_5;
    wire iwcount_6;
    wire iwcount_7;
    wire co2_3;
    wire wcount_6;
    wire wcount_7;
    wire iwcount_8;
    wire iwcount_9;
    wire co3_3;
    wire wcount_8;
    wire wcount_9;
    wire iwcount_10;
    wire iwcount_11;
    wire co4_3;
    wire wcount_10;
    wire wcount_11;
    wire iwcount_12;
    wire co6_1;
    wire co5_3;
    wire wcount_12;
    wire scuba_vhi;
    wire ircount_0;
    wire ircount_1;
    wire r_ctr_ci;
    wire rcount_0;
    wire rcount_1;
    wire ircount_2;
    wire ircount_3;
    wire co0_4;
    wire rcount_2;
    wire rcount_3;
    wire ircount_4;
    wire ircount_5;
    wire co1_4;
    wire rcount_4;
    wire rcount_5;
    wire ircount_6;
    wire ircount_7;
    wire co2_4;
    wire rcount_6;
    wire rcount_7;
    wire ircount_8;
    wire ircount_9;
    wire co3_4;
    wire rcount_8;
    wire rcount_9;
    wire ircount_10;
    wire ircount_11;
    wire co4_4;
    wire rcount_10;
    wire rcount_11;
    wire ircount_12;
    wire co6_2;
    wire co5_4;
    wire rcount_12;
    wire scuba_vlo;

    AND2 AND2_t3 (.A(WrEn), .B(invout_1), .Z(wren_i));

    INV INV_3 (.A(full_i), .Z(invout_1));

    AND2 AND2_t2 (.A(RdEn), .B(invout_0), .Z(rden_i));

    INV INV_2 (.A(empty_i), .Z(invout_0));

    AND2 AND2_t1 (.A(wren_i), .B(rden_i_inv), .Z(cnt_con));

    XOR2 XOR2_t0 (.A(wren_i), .B(rden_i), .Z(fcnt_en));

    INV INV_1 (.A(rden_i), .Z(rden_i_inv));

    INV INV_0 (.A(wren_i), .Z(wren_i_inv));

    // synopsys translate_off
    defparam LUT4_1.initval =  16'h3232 ;
    // synopsys translate_on
    ROM16X1 LUT4_1 (.AD3(scuba_vlo), .AD2(cmp_le_1), .AD1(wren_i), .AD0(empty_i), 
        .DO0(empty_d))
             /* synthesis initval="0x3232" */;

    // synopsys translate_off
    defparam LUT4_0.initval =  16'h3232 ;
    // synopsys translate_on
    ROM16X1 LUT4_0 (.AD3(scuba_vlo), .AD2(cmp_ge_d1), .AD1(rden_i), .AD0(full_i), 
        .DO0(full_d))
             /* synthesis initval="0x3232" */;

    // synopsys translate_off
    defparam pdp_ram_0_0_3.CSDECODE_B =  3'b001 ;
    defparam pdp_ram_0_0_3.CSDECODE_A =  3'b000 ;
    defparam pdp_ram_0_0_3.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_0_0_3.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_0_0_3.GSR = "DISABLED" ;
    defparam pdp_ram_0_0_3.RESETMODE = "ASYNC" ;
    defparam pdp_ram_0_0_3.REGMODE_B = "OUTREG" ;
    defparam pdp_ram_0_0_3.REGMODE_A = "OUTREG" ;
    defparam pdp_ram_0_0_3.DATA_WIDTH_B = 4 ;
    defparam pdp_ram_0_0_3.DATA_WIDTH_A = 4 ;
    // synopsys translate_on
    DP16KB pdp_ram_0_0_3 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(scuba_vlo), .DIA5(scuba_vlo), .DIA6(scuba_vlo), 
        .DIA7(scuba_vlo), .DIA8(scuba_vlo), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(wcount_0), .ADA3(wcount_1), .ADA4(wcount_2), 
        .ADA5(wcount_3), .ADA6(wcount_4), .ADA7(wcount_5), .ADA8(wcount_6), 
        .ADA9(wcount_7), .ADA10(wcount_8), .ADA11(wcount_9), .ADA12(wcount_10), 
        .ADA13(wcount_11), .CEA(wren_i), .CLKA(Clock), .WEA(scuba_vhi), 
        .CSA0(scuba_vlo), .CSA1(scuba_vlo), .CSA2(scuba_vlo), .RSTA(Reset), 
        .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), .DIB3(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(scuba_vlo), 
        .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(scuba_vlo), 
        .ADB2(rcount_0), .ADB3(rcount_1), .ADB4(rcount_2), .ADB5(rcount_3), 
        .ADB6(rcount_4), .ADB7(rcount_5), .ADB8(rcount_6), .ADB9(rcount_7), 
        .ADB10(rcount_8), .ADB11(rcount_9), .ADB12(rcount_10), .ADB13(rcount_11), 
        .CEB(scuba_vhi), .CLKB(Clock), .WEB(scuba_vlo), .CSB0(rden_i), .CSB1(scuba_vlo), 
        .CSB2(scuba_vlo), .RSTB(Reset), .DOA0(), .DOA1(), .DOA2(), .DOA3(), 
        .DOA4(), .DOA5(), .DOA6(), .DOA7(), .DOA8(), .DOA9(), .DOA10(), 
        .DOA11(), .DOA12(), .DOA13(), .DOA14(), .DOA15(), .DOA16(), .DOA17(), 
        .DOB0(Q[0]), .DOB1(Q[1]), .DOB2(Q[2]), .DOB3(Q[3]), .DOB4(), .DOB5(), 
        .DOB6(), .DOB7(), .DOB8(), .DOB9(), .DOB10(), .DOB11(), .DOB12(), 
        .DOB13(), .DOB14(), .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="FIFO.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_B="0b001" */
             /* synthesis CSDECODE_A="0b000" */
             /* synthesis WRITEMODE_B="NORMAL" */
             /* synthesis WRITEMODE_A="NORMAL" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="ASYNC" */
             /* synthesis REGMODE_B="OUTREG" */
             /* synthesis REGMODE_A="OUTREG" */
             /* synthesis DATA_WIDTH_B="4" */
             /* synthesis DATA_WIDTH_A="4" */;

    // synopsys translate_off
    defparam pdp_ram_0_1_2.CSDECODE_B =  3'b001 ;
    defparam pdp_ram_0_1_2.CSDECODE_A =  3'b000 ;
    defparam pdp_ram_0_1_2.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_0_1_2.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_0_1_2.GSR = "DISABLED" ;
    defparam pdp_ram_0_1_2.RESETMODE = "ASYNC" ;
    defparam pdp_ram_0_1_2.REGMODE_B = "OUTREG" ;
    defparam pdp_ram_0_1_2.REGMODE_A = "OUTREG" ;
    defparam pdp_ram_0_1_2.DATA_WIDTH_B = 4 ;
    defparam pdp_ram_0_1_2.DATA_WIDTH_A = 4 ;
    // synopsys translate_on
    DP16KB pdp_ram_0_1_2 (.DIA0(Data[4]), .DIA1(Data[5]), .DIA2(Data[6]), 
        .DIA3(Data[7]), .DIA4(scuba_vlo), .DIA5(scuba_vlo), .DIA6(scuba_vlo), 
        .DIA7(scuba_vlo), .DIA8(scuba_vlo), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(wcount_0), .ADA3(wcount_1), .ADA4(wcount_2), 
        .ADA5(wcount_3), .ADA6(wcount_4), .ADA7(wcount_5), .ADA8(wcount_6), 
        .ADA9(wcount_7), .ADA10(wcount_8), .ADA11(wcount_9), .ADA12(wcount_10), 
        .ADA13(wcount_11), .CEA(wren_i), .CLKA(Clock), .WEA(scuba_vhi), 
        .CSA0(scuba_vlo), .CSA1(scuba_vlo), .CSA2(scuba_vlo), .RSTA(Reset), 
        .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), .DIB3(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(scuba_vlo), 
        .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(scuba_vlo), 
        .ADB2(rcount_0), .ADB3(rcount_1), .ADB4(rcount_2), .ADB5(rcount_3), 
        .ADB6(rcount_4), .ADB7(rcount_5), .ADB8(rcount_6), .ADB9(rcount_7), 
        .ADB10(rcount_8), .ADB11(rcount_9), .ADB12(rcount_10), .ADB13(rcount_11), 
        .CEB(scuba_vhi), .CLKB(Clock), .WEB(scuba_vlo), .CSB0(rden_i), .CSB1(scuba_vlo), 
        .CSB2(scuba_vlo), .RSTB(Reset), .DOA0(), .DOA1(), .DOA2(), .DOA3(), 
        .DOA4(), .DOA5(), .DOA6(), .DOA7(), .DOA8(), .DOA9(), .DOA10(), 
        .DOA11(), .DOA12(), .DOA13(), .DOA14(), .DOA15(), .DOA16(), .DOA17(), 
        .DOB0(Q[4]), .DOB1(Q[5]), .DOB2(Q[6]), .DOB3(Q[7]), .DOB4(), .DOB5(), 
        .DOB6(), .DOB7(), .DOB8(), .DOB9(), .DOB10(), .DOB11(), .DOB12(), 
        .DOB13(), .DOB14(), .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="FIFO.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_B="0b001" */
             /* synthesis CSDECODE_A="0b000" */
             /* synthesis WRITEMODE_B="NORMAL" */
             /* synthesis WRITEMODE_A="NORMAL" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="ASYNC" */
             /* synthesis REGMODE_B="OUTREG" */
             /* synthesis REGMODE_A="OUTREG" */
             /* synthesis DATA_WIDTH_B="4" */
             /* synthesis DATA_WIDTH_A="4" */;

    // synopsys translate_off
    defparam pdp_ram_0_2_1.CSDECODE_B =  3'b001 ;
    defparam pdp_ram_0_2_1.CSDECODE_A =  3'b000 ;
    defparam pdp_ram_0_2_1.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_0_2_1.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_0_2_1.GSR = "DISABLED" ;
    defparam pdp_ram_0_2_1.RESETMODE = "ASYNC" ;
    defparam pdp_ram_0_2_1.REGMODE_B = "OUTREG" ;
    defparam pdp_ram_0_2_1.REGMODE_A = "OUTREG" ;
    defparam pdp_ram_0_2_1.DATA_WIDTH_B = 4 ;
    defparam pdp_ram_0_2_1.DATA_WIDTH_A = 4 ;
    // synopsys translate_on
    DP16KB pdp_ram_0_2_1 (.DIA0(Data[8]), .DIA1(Data[9]), .DIA2(Data[10]), 
        .DIA3(Data[11]), .DIA4(scuba_vlo), .DIA5(scuba_vlo), .DIA6(scuba_vlo), 
        .DIA7(scuba_vlo), .DIA8(scuba_vlo), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(wcount_0), .ADA3(wcount_1), .ADA4(wcount_2), 
        .ADA5(wcount_3), .ADA6(wcount_4), .ADA7(wcount_5), .ADA8(wcount_6), 
        .ADA9(wcount_7), .ADA10(wcount_8), .ADA11(wcount_9), .ADA12(wcount_10), 
        .ADA13(wcount_11), .CEA(wren_i), .CLKA(Clock), .WEA(scuba_vhi), 
        .CSA0(scuba_vlo), .CSA1(scuba_vlo), .CSA2(scuba_vlo), .RSTA(Reset), 
        .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), .DIB3(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(scuba_vlo), 
        .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(scuba_vlo), 
        .ADB2(rcount_0), .ADB3(rcount_1), .ADB4(rcount_2), .ADB5(rcount_3), 
        .ADB6(rcount_4), .ADB7(rcount_5), .ADB8(rcount_6), .ADB9(rcount_7), 
        .ADB10(rcount_8), .ADB11(rcount_9), .ADB12(rcount_10), .ADB13(rcount_11), 
        .CEB(scuba_vhi), .CLKB(Clock), .WEB(scuba_vlo), .CSB0(rden_i), .CSB1(scuba_vlo), 
        .CSB2(scuba_vlo), .RSTB(Reset), .DOA0(), .DOA1(), .DOA2(), .DOA3(), 
        .DOA4(), .DOA5(), .DOA6(), .DOA7(), .DOA8(), .DOA9(), .DOA10(), 
        .DOA11(), .DOA12(), .DOA13(), .DOA14(), .DOA15(), .DOA16(), .DOA17(), 
        .DOB0(Q[8]), .DOB1(Q[9]), .DOB2(Q[10]), .DOB3(Q[11]), .DOB4(), .DOB5(), 
        .DOB6(), .DOB7(), .DOB8(), .DOB9(), .DOB10(), .DOB11(), .DOB12(), 
        .DOB13(), .DOB14(), .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="FIFO.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_B="0b001" */
             /* synthesis CSDECODE_A="0b000" */
             /* synthesis WRITEMODE_B="NORMAL" */
             /* synthesis WRITEMODE_A="NORMAL" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="ASYNC" */
             /* synthesis REGMODE_B="OUTREG" */
             /* synthesis REGMODE_A="OUTREG" */
             /* synthesis DATA_WIDTH_B="4" */
             /* synthesis DATA_WIDTH_A="4" */;

    // synopsys translate_off
    defparam pdp_ram_0_3_0.CSDECODE_B =  3'b001 ;
    defparam pdp_ram_0_3_0.CSDECODE_A =  3'b000 ;
    defparam pdp_ram_0_3_0.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_0_3_0.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_0_3_0.GSR = "DISABLED" ;
    defparam pdp_ram_0_3_0.RESETMODE = "ASYNC" ;
    defparam pdp_ram_0_3_0.REGMODE_B = "OUTREG" ;
    defparam pdp_ram_0_3_0.REGMODE_A = "OUTREG" ;
    defparam pdp_ram_0_3_0.DATA_WIDTH_B = 4 ;
    defparam pdp_ram_0_3_0.DATA_WIDTH_A = 4 ;
    // synopsys translate_on
    DP16KB pdp_ram_0_3_0 (.DIA0(Data[12]), .DIA1(Data[13]), .DIA2(Data[14]), 
        .DIA3(Data[15]), .DIA4(scuba_vlo), .DIA5(scuba_vlo), .DIA6(scuba_vlo), 
        .DIA7(scuba_vlo), .DIA8(scuba_vlo), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(wcount_0), .ADA3(wcount_1), .ADA4(wcount_2), 
        .ADA5(wcount_3), .ADA6(wcount_4), .ADA7(wcount_5), .ADA8(wcount_6), 
        .ADA9(wcount_7), .ADA10(wcount_8), .ADA11(wcount_9), .ADA12(wcount_10), 
        .ADA13(wcount_11), .CEA(wren_i), .CLKA(Clock), .WEA(scuba_vhi), 
        .CSA0(scuba_vlo), .CSA1(scuba_vlo), .CSA2(scuba_vlo), .RSTA(Reset), 
        .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), .DIB3(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(scuba_vlo), 
        .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(scuba_vlo), 
        .ADB2(rcount_0), .ADB3(rcount_1), .ADB4(rcount_2), .ADB5(rcount_3), 
        .ADB6(rcount_4), .ADB7(rcount_5), .ADB8(rcount_6), .ADB9(rcount_7), 
        .ADB10(rcount_8), .ADB11(rcount_9), .ADB12(rcount_10), .ADB13(rcount_11), 
        .CEB(scuba_vhi), .CLKB(Clock), .WEB(scuba_vlo), .CSB0(rden_i), .CSB1(scuba_vlo), 
        .CSB2(scuba_vlo), .RSTB(Reset), .DOA0(), .DOA1(), .DOA2(), .DOA3(), 
        .DOA4(), .DOA5(), .DOA6(), .DOA7(), .DOA8(), .DOA9(), .DOA10(), 
        .DOA11(), .DOA12(), .DOA13(), .DOA14(), .DOA15(), .DOA16(), .DOA17(), 
        .DOB0(Q[12]), .DOB1(Q[13]), .DOB2(Q[14]), .DOB3(Q[15]), .DOB4(), 
        .DOB5(), .DOB6(), .DOB7(), .DOB8(), .DOB9(), .DOB10(), .DOB11(), 
        .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="FIFO.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_B="0b001" */
             /* synthesis CSDECODE_A="0b000" */
             /* synthesis WRITEMODE_B="NORMAL" */
             /* synthesis WRITEMODE_A="NORMAL" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="ASYNC" */
             /* synthesis REGMODE_B="OUTREG" */
             /* synthesis REGMODE_A="OUTREG" */
             /* synthesis DATA_WIDTH_B="4" */
             /* synthesis DATA_WIDTH_A="4" */;

    // synopsys translate_off
    defparam FF_40.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_40 (.D(ifcount_0), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_0))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_39.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_39 (.D(ifcount_1), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_38.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_38 (.D(ifcount_2), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_2))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_37.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_37 (.D(ifcount_3), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_3))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_36.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_36 (.D(ifcount_4), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_4))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_35.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_35 (.D(ifcount_5), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_5))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_34.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_34 (.D(ifcount_6), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_6))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_33.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_33 (.D(ifcount_7), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_7))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_32.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_32 (.D(ifcount_8), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_8))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_31.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_31 (.D(ifcount_9), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_9))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_30.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_30 (.D(ifcount_10), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_10))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_29.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_29 (.D(ifcount_11), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_11))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_28.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_28 (.D(ifcount_12), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_12))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_27.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1S3BX FF_27 (.D(empty_d), .CK(Clock), .PD(Reset), .Q(empty_i))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_26.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1S3DX FF_26 (.D(full_d), .CK(Clock), .CD(Reset), .Q(full_i))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_25.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_25 (.D(iwcount_0), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_0))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_24.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_24 (.D(iwcount_1), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_23.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_23 (.D(iwcount_2), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_2))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_22.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_22 (.D(iwcount_3), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_3))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_21.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_21 (.D(iwcount_4), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_4))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_20.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_20 (.D(iwcount_5), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_5))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_19.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_19 (.D(iwcount_6), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_6))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_18.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_18 (.D(iwcount_7), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_7))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_17.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_17 (.D(iwcount_8), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_8))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_16.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_16 (.D(iwcount_9), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_9))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_15.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_15 (.D(iwcount_10), .SP(wren_i), .CK(Clock), .CD(Reset), 
        .Q(wcount_10))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_14.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_14 (.D(iwcount_11), .SP(wren_i), .CK(Clock), .CD(Reset), 
        .Q(wcount_11))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_13.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_13 (.D(iwcount_12), .SP(wren_i), .CK(Clock), .CD(Reset), 
        .Q(wcount_12))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_12.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_12 (.D(ircount_0), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_0))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_11.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_11 (.D(ircount_1), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_10.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_10 (.D(ircount_2), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_2))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_9.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_9 (.D(ircount_3), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_3))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_8.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_8 (.D(ircount_4), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_4))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_7.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_7 (.D(ircount_5), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_5))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_6.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_6 (.D(ircount_6), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_6))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_5.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_5 (.D(ircount_7), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_7))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_4.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_4 (.D(ircount_8), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_8))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_3.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_3 (.D(ircount_9), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_9))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_2.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_2 (.D(ircount_10), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_10))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_1.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_1 (.D(ircount_11), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_11))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_0.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_0 (.D(ircount_12), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_12))
             /* synthesis GSR="ENABLED" */;

    FADD2B bdcnt_bctr_cia (.A0(scuba_vlo), .A1(cnt_con), .B0(scuba_vlo), 
        .B1(cnt_con), .CI(scuba_vlo), .COUT(bdcnt_bctr_ci), .S0(), .S1());

    CB2 bdcnt_bctr_0 (.CI(bdcnt_bctr_ci), .PC0(fcount_0), .PC1(fcount_1), 
        .CON(cnt_con), .CO(co0), .NC0(ifcount_0), .NC1(ifcount_1));

    CB2 bdcnt_bctr_1 (.CI(co0), .PC0(fcount_2), .PC1(fcount_3), .CON(cnt_con), 
        .CO(co1), .NC0(ifcount_2), .NC1(ifcount_3));

    CB2 bdcnt_bctr_2 (.CI(co1), .PC0(fcount_4), .PC1(fcount_5), .CON(cnt_con), 
        .CO(co2), .NC0(ifcount_4), .NC1(ifcount_5));

    CB2 bdcnt_bctr_3 (.CI(co2), .PC0(fcount_6), .PC1(fcount_7), .CON(cnt_con), 
        .CO(co3), .NC0(ifcount_6), .NC1(ifcount_7));

    CB2 bdcnt_bctr_4 (.CI(co3), .PC0(fcount_8), .PC1(fcount_9), .CON(cnt_con), 
        .CO(co4), .NC0(ifcount_8), .NC1(ifcount_9));

    CB2 bdcnt_bctr_5 (.CI(co4), .PC0(fcount_10), .PC1(fcount_11), .CON(cnt_con), 
        .CO(co5), .NC0(ifcount_10), .NC1(ifcount_11));

    CB2 bdcnt_bctr_6 (.CI(co5), .PC0(fcount_12), .PC1(scuba_vlo), .CON(cnt_con), 
        .CO(co6), .NC0(ifcount_12), .NC1());

    FADD2B e_cmp_ci_a (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), .B1(scuba_vhi), 
        .CI(scuba_vlo), .COUT(cmp_ci), .S0(), .S1());

    ALEB2 e_cmp_0 (.A0(fcount_0), .A1(fcount_1), .B0(rden_i), .B1(scuba_vlo), 
        .CI(cmp_ci), .LE(co0_1));

    ALEB2 e_cmp_1 (.A0(fcount_2), .A1(fcount_3), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(co0_1), .LE(co1_1));

    ALEB2 e_cmp_2 (.A0(fcount_4), .A1(fcount_5), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(co1_1), .LE(co2_1));

    ALEB2 e_cmp_3 (.A0(fcount_6), .A1(fcount_7), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(co2_1), .LE(co3_1));

    ALEB2 e_cmp_4 (.A0(fcount_8), .A1(fcount_9), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(co3_1), .LE(co4_1));

    ALEB2 e_cmp_5 (.A0(fcount_10), .A1(fcount_11), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(co4_1), .LE(co5_1));

    ALEB2 e_cmp_6 (.A0(fcount_12), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(co5_1), .LE(cmp_le_1_c));

    FADD2B a0 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(cmp_le_1_c), .COUT(), .S0(cmp_le_1), .S1());

    FADD2B g_cmp_ci_a (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), .B1(scuba_vhi), 
        .CI(scuba_vlo), .COUT(cmp_ci_1), .S0(), .S1());

    AGEB2 g_cmp_0 (.A0(fcount_0), .A1(fcount_1), .B0(wren_i), .B1(wren_i), 
        .CI(cmp_ci_1), .GE(co0_2));

    AGEB2 g_cmp_1 (.A0(fcount_2), .A1(fcount_3), .B0(wren_i), .B1(wren_i), 
        .CI(co0_2), .GE(co1_2));

    AGEB2 g_cmp_2 (.A0(fcount_4), .A1(fcount_5), .B0(wren_i), .B1(wren_i), 
        .CI(co1_2), .GE(co2_2));

    AGEB2 g_cmp_3 (.A0(fcount_6), .A1(fcount_7), .B0(wren_i), .B1(wren_i), 
        .CI(co2_2), .GE(co3_2));

    AGEB2 g_cmp_4 (.A0(fcount_8), .A1(fcount_9), .B0(wren_i), .B1(wren_i), 
        .CI(co3_2), .GE(co4_2));

    AGEB2 g_cmp_5 (.A0(fcount_10), .A1(fcount_11), .B0(wren_i), .B1(wren_i), 
        .CI(co4_2), .GE(co5_2));

    AGEB2 g_cmp_6 (.A0(fcount_12), .A1(scuba_vlo), .B0(wren_i_inv), .B1(scuba_vlo), 
        .CI(co5_2), .GE(cmp_ge_d1_c));

    FADD2B a1 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(cmp_ge_d1_c), .COUT(), .S0(cmp_ge_d1), .S1());

    FADD2B w_ctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .CI(scuba_vlo), .COUT(w_ctr_ci), .S0(), .S1());

    CU2 w_ctr_0 (.CI(w_ctr_ci), .PC0(wcount_0), .PC1(wcount_1), .CO(co0_3), 
        .NC0(iwcount_0), .NC1(iwcount_1));

    CU2 w_ctr_1 (.CI(co0_3), .PC0(wcount_2), .PC1(wcount_3), .CO(co1_3), 
        .NC0(iwcount_2), .NC1(iwcount_3));

    CU2 w_ctr_2 (.CI(co1_3), .PC0(wcount_4), .PC1(wcount_5), .CO(co2_3), 
        .NC0(iwcount_4), .NC1(iwcount_5));

    CU2 w_ctr_3 (.CI(co2_3), .PC0(wcount_6), .PC1(wcount_7), .CO(co3_3), 
        .NC0(iwcount_6), .NC1(iwcount_7));

    CU2 w_ctr_4 (.CI(co3_3), .PC0(wcount_8), .PC1(wcount_9), .CO(co4_3), 
        .NC0(iwcount_8), .NC1(iwcount_9));

    CU2 w_ctr_5 (.CI(co4_3), .PC0(wcount_10), .PC1(wcount_11), .CO(co5_3), 
        .NC0(iwcount_10), .NC1(iwcount_11));

    CU2 w_ctr_6 (.CI(co5_3), .PC0(wcount_12), .PC1(scuba_vlo), .CO(co6_1), 
        .NC0(iwcount_12), .NC1());

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    FADD2B r_ctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .CI(scuba_vlo), .COUT(r_ctr_ci), .S0(), .S1());

    CU2 r_ctr_0 (.CI(r_ctr_ci), .PC0(rcount_0), .PC1(rcount_1), .CO(co0_4), 
        .NC0(ircount_0), .NC1(ircount_1));

    CU2 r_ctr_1 (.CI(co0_4), .PC0(rcount_2), .PC1(rcount_3), .CO(co1_4), 
        .NC0(ircount_2), .NC1(ircount_3));

    CU2 r_ctr_2 (.CI(co1_4), .PC0(rcount_4), .PC1(rcount_5), .CO(co2_4), 
        .NC0(ircount_4), .NC1(ircount_5));

    CU2 r_ctr_3 (.CI(co2_4), .PC0(rcount_6), .PC1(rcount_7), .CO(co3_4), 
        .NC0(ircount_6), .NC1(ircount_7));

    CU2 r_ctr_4 (.CI(co3_4), .PC0(rcount_8), .PC1(rcount_9), .CO(co4_4), 
        .NC0(ircount_8), .NC1(ircount_9));

    CU2 r_ctr_5 (.CI(co4_4), .PC0(rcount_10), .PC1(rcount_11), .CO(co5_4), 
        .NC0(ircount_10), .NC1(ircount_11));

    CU2 r_ctr_6 (.CI(co5_4), .PC0(rcount_12), .PC1(scuba_vlo), .CO(co6_2), 
        .NC0(ircount_12), .NC1());

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    assign WCNT[0] = fcount_0;
    assign WCNT[1] = fcount_1;
    assign WCNT[2] = fcount_2;
    assign WCNT[3] = fcount_3;
    assign WCNT[4] = fcount_4;
    assign WCNT[5] = fcount_5;
    assign WCNT[6] = fcount_6;
    assign WCNT[7] = fcount_7;
    assign WCNT[8] = fcount_8;
    assign WCNT[9] = fcount_9;
    assign WCNT[10] = fcount_10;
    assign WCNT[11] = fcount_11;
    assign WCNT[12] = fcount_12;
    assign Empty = empty_i;
    assign Full = full_i;


    // exemplar begin
    // exemplar attribute LUT4_1 initval 0x3232
    // exemplar attribute LUT4_0 initval 0x3232
    // exemplar attribute pdp_ram_0_0_3 MEM_LPC_FILE FIFO.lpc
    // exemplar attribute pdp_ram_0_0_3 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_0_3 CSDECODE_B 0b001
    // exemplar attribute pdp_ram_0_0_3 CSDECODE_A 0b000
    // exemplar attribute pdp_ram_0_0_3 WRITEMODE_B NORMAL
    // exemplar attribute pdp_ram_0_0_3 WRITEMODE_A NORMAL
    // exemplar attribute pdp_ram_0_0_3 GSR DISABLED
    // exemplar attribute pdp_ram_0_0_3 RESETMODE ASYNC
    // exemplar attribute pdp_ram_0_0_3 REGMODE_B OUTREG
    // exemplar attribute pdp_ram_0_0_3 REGMODE_A OUTREG
    // exemplar attribute pdp_ram_0_0_3 DATA_WIDTH_B 4
    // exemplar attribute pdp_ram_0_0_3 DATA_WIDTH_A 4
    // exemplar attribute pdp_ram_0_1_2 MEM_LPC_FILE FIFO.lpc
    // exemplar attribute pdp_ram_0_1_2 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_1_2 CSDECODE_B 0b001
    // exemplar attribute pdp_ram_0_1_2 CSDECODE_A 0b000
    // exemplar attribute pdp_ram_0_1_2 WRITEMODE_B NORMAL
    // exemplar attribute pdp_ram_0_1_2 WRITEMODE_A NORMAL
    // exemplar attribute pdp_ram_0_1_2 GSR DISABLED
    // exemplar attribute pdp_ram_0_1_2 RESETMODE ASYNC
    // exemplar attribute pdp_ram_0_1_2 REGMODE_B OUTREG
    // exemplar attribute pdp_ram_0_1_2 REGMODE_A OUTREG
    // exemplar attribute pdp_ram_0_1_2 DATA_WIDTH_B 4
    // exemplar attribute pdp_ram_0_1_2 DATA_WIDTH_A 4
    // exemplar attribute pdp_ram_0_2_1 MEM_LPC_FILE FIFO.lpc
    // exemplar attribute pdp_ram_0_2_1 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_2_1 CSDECODE_B 0b001
    // exemplar attribute pdp_ram_0_2_1 CSDECODE_A 0b000
    // exemplar attribute pdp_ram_0_2_1 WRITEMODE_B NORMAL
    // exemplar attribute pdp_ram_0_2_1 WRITEMODE_A NORMAL
    // exemplar attribute pdp_ram_0_2_1 GSR DISABLED
    // exemplar attribute pdp_ram_0_2_1 RESETMODE ASYNC
    // exemplar attribute pdp_ram_0_2_1 REGMODE_B OUTREG
    // exemplar attribute pdp_ram_0_2_1 REGMODE_A OUTREG
    // exemplar attribute pdp_ram_0_2_1 DATA_WIDTH_B 4
    // exemplar attribute pdp_ram_0_2_1 DATA_WIDTH_A 4
    // exemplar attribute pdp_ram_0_3_0 MEM_LPC_FILE FIFO.lpc
    // exemplar attribute pdp_ram_0_3_0 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_3_0 CSDECODE_B 0b001
    // exemplar attribute pdp_ram_0_3_0 CSDECODE_A 0b000
    // exemplar attribute pdp_ram_0_3_0 WRITEMODE_B NORMAL
    // exemplar attribute pdp_ram_0_3_0 WRITEMODE_A NORMAL
    // exemplar attribute pdp_ram_0_3_0 GSR DISABLED
    // exemplar attribute pdp_ram_0_3_0 RESETMODE ASYNC
    // exemplar attribute pdp_ram_0_3_0 REGMODE_B OUTREG
    // exemplar attribute pdp_ram_0_3_0 REGMODE_A OUTREG
    // exemplar attribute pdp_ram_0_3_0 DATA_WIDTH_B 4
    // exemplar attribute pdp_ram_0_3_0 DATA_WIDTH_A 4
    // exemplar attribute FF_40 GSR ENABLED
    // exemplar attribute FF_39 GSR ENABLED
    // exemplar attribute FF_38 GSR ENABLED
    // exemplar attribute FF_37 GSR ENABLED
    // exemplar attribute FF_36 GSR ENABLED
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
